-- Convert full state names to 2-letter abbreviations
UPDATE "Politician" SET state = 'AL' WHERE state = 'Alabama';
UPDATE "Politician" SET state = 'AK' WHERE state = 'Alaska';
UPDATE "Politician" SET state = 'AZ' WHERE state = 'Arizona';
UPDATE "Politician" SET state = 'AR' WHERE state = 'Arkansas';
UPDATE "Politician" SET state = 'CA' WHERE state = 'California';
UPDATE "Politician" SET state = 'CO' WHERE state = 'Colorado';
UPDATE "Politician" SET state = 'CT' WHERE state = 'Connecticut';
UPDATE "Politician" SET state = 'DE' WHERE state = 'Delaware';
UPDATE "Politician" SET state = 'FL' WHERE state = 'Florida';
UPDATE "Politician" SET state = 'GA' WHERE state = 'Georgia';
UPDATE "Politician" SET state = 'HI' WHERE state = 'Hawaii';
UPDATE "Politician" SET state = 'ID' WHERE state = 'Idaho';
UPDATE "Politician" SET state = 'IL' WHERE state = 'Illinois';
UPDATE "Politician" SET state = 'IN' WHERE state = 'Indiana';
UPDATE "Politician" SET state = 'IA' WHERE state = 'Iowa';
UPDATE "Politician" SET state = 'KS' WHERE state = 'Kansas';
UPDATE "Politician" SET state = 'KY' WHERE state = 'Kentucky';
UPDATE "Politician" SET state = 'LA' WHERE state = 'Louisiana';
UPDATE "Politician" SET state = 'ME' WHERE state = 'Maine';
UPDATE "Politician" SET state = 'MD' WHERE state = 'Maryland';
UPDATE "Politician" SET state = 'MA' WHERE state = 'Massachusetts';
UPDATE "Politician" SET state = 'MI' WHERE state = 'Michigan';
UPDATE "Politician" SET state = 'MN' WHERE state = 'Minnesota';
UPDATE "Politician" SET state = 'MS' WHERE state = 'Mississippi';
UPDATE "Politician" SET state = 'MO' WHERE state = 'Missouri';
UPDATE "Politician" SET state = 'MT' WHERE state = 'Montana';
UPDATE "Politician" SET state = 'NE' WHERE state = 'Nebraska';
UPDATE "Politician" SET state = 'NV' WHERE state = 'Nevada';
UPDATE "Politician" SET state = 'NH' WHERE state = 'New Hampshire';
UPDATE "Politician" SET state = 'NJ' WHERE state = 'New Jersey';
UPDATE "Politician" SET state = 'NM' WHERE state = 'New Mexico';
UPDATE "Politician" SET state = 'NY' WHERE state = 'New York';
UPDATE "Politician" SET state = 'NC' WHERE state = 'North Carolina';
UPDATE "Politician" SET state = 'ND' WHERE state = 'North Dakota';
UPDATE "Politician" SET state = 'OH' WHERE state = 'Ohio';
UPDATE "Politician" SET state = 'OK' WHERE state = 'Oklahoma';
UPDATE "Politician" SET state = 'OR' WHERE state = 'Oregon';
UPDATE "Politician" SET state = 'PA' WHERE state = 'Pennsylvania';
UPDATE "Politician" SET state = 'RI' WHERE state = 'Rhode Island';
UPDATE "Politician" SET state = 'SC' WHERE state = 'South Carolina';
UPDATE "Politician" SET state = 'SD' WHERE state = 'South Dakota';
UPDATE "Politician" SET state = 'TN' WHERE state = 'Tennessee';
UPDATE "Politician" SET state = 'TX' WHERE state = 'Texas';
UPDATE "Politician" SET state = 'UT' WHERE state = 'Utah';
UPDATE "Politician" SET state = 'VT' WHERE state = 'Vermont';
UPDATE "Politician" SET state = 'VA' WHERE state = 'Virginia';
UPDATE "Politician" SET state = 'WA' WHERE state = 'Washington';
UPDATE "Politician" SET state = 'WV' WHERE state = 'West Virginia';
UPDATE "Politician" SET state = 'WI' WHERE state = 'Wisconsin';
UPDATE "Politician" SET state = 'WY' WHERE state = 'Wyoming';

-- AlterTable - Change state column to VARCHAR(2)
ALTER TABLE "Politician" ALTER COLUMN "state" SET DATA TYPE VARCHAR(2);
